### ISSUE TITLE
zerobuf used even when disabled

### ISSUE THREAD

**Issue by ingowald** [BlueBrain/Brayns#100]
When subproject_zerobuf is disabled, some code still thinks it's enabled, then fails

[ 64%] Building CXX object brayns/common/CMakeFiles/braynsCommon.dir/camera/Camera.cpp.o
/home/wald/Projects/Brayns/brayns/common/camera/Camera.cpp:25:37: fatal error: zerobuf/render/camera.h: No such file or directory
compilation terminated.

**Comment by ingowald** [comment]
Actually that error exists even if zerobuf is enabled - seems this camera.h file is simply missing from zerobuf. :-/

**Comment by favreau** [comment]
Working on it, will be merge today :-)

**Comment by favreau** [comment]
Fixed by https://github.com/BlueBrain/Brayns/pull/107
