### ISSUE TITLE
assimp

### ISSUE THREAD

**Issue by ingowald** [BlueBrain/Brayns#101]
brayns mesh loader requires assimp, but doesn't check for it in cmakefile - simply creates link error after compiling.

**Comment by favreau** [comment]
Currently fixing it. it will be merged today. Note that the assimp system package is broken on Ubuntu 14.04, and I had to recompile it from the source to make it work on my box. That appears to be fixed on Ubuntu 16.04

**Comment by favreau** [comment]
Fixed by https://github.com/BlueBrain/Brayns/pull/107
