### ISSUE TITLE
docker image fails to run

### ISSUE THREAD

**Issue by theAeon** [BlueBrain/Brayns#1069]
**Describe the bug**
Running on virtualized x86_64 (across two distinct environments) errors out with ```braynsService: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory```

**To Reproduce**
1. ```docker pull blubrain/brayns```
2. ```docker run -ti --rm -p 8200:8200 bluebrain/brayns```

**Expected behavior**
The brayns container launches normally.

**Additional context**
Has occurred in two separate environments: 
1. Flatcar Linux w/ docker running under the XCP-ng hypervisor using the pulled image 
2. OpenSUSE Tumbleweed w/ containerd under WSL 2 using both a built image and the pulled image.

**Comment by NadirRoGue** [comment]
Dear @theAeon ,

I confirmed this issue (It actually happened running the image on any platform). PR https://github.com/BlueBrain/Brayns/pull/1071 should fix it, and it is already merged on the develop branch (furthermore, the dockehub latest tag should be pushed and updated in the next hours).

Please, let me know if this works for you.

**Comment by theAeon** [comment]
It starts now but I do seem to be getting a bunch of method not found errors when connecting the UI to it. Is that supposed to happen with the bare images?

**Comment by NadirRoGue** [comment]
I guess the UI you are using is this one: https://hub.docker.com/r/bluebrain/brayns-ui/
This image, however, is only compatible with brayns up to version 1.1. Brayns version 2.0 and above (including latest) is not compatible with it, and there is not UI image available for these versions yet.

You can still use the latest version of brayns through the python API (you can find further information on the README and in the python folder of the source code of Brayns).

**Comment by theAeon** [comment]
Gotcha. Thanks for the clarification.
