### ISSUE TITLE
AtlasExplorer can't find bzlib.h while compiling (Bzip2 build from source, installed in custom directory)

### ISSUE THREAD

**Issue by mahechine** [BlueBrain/Brayns#1191]
[ 87%] Building CXX object plugins/AtlasExplorer/CMakeFiles/braynsAtlasExplorer.dir/io/nrrdloader/data/decompressors/BZip2Decompressor.cpp.o

Brayns/plugins/AtlasExplorer/io/nrrdloader/data/decompressors/BZip2Decompressor.cpp:25:10: fatal error: bzlib.h: No such file or directory
   25 | #include <bzlib.h>
      |          ^~~~~~~~~
compilation terminated.

I built Bzip2 from source ( gitlab.com/bzip2/bzip2 ), and installed in a custom directory

**Comment by mahechine** [comment]
I reinstalled bzip2 in /usr/local and this time compilation finished successfully.

It appeals that the cmake BZIP2_INCLUDE_DIR is not correctly added to project include directories.

**Comment by NadirRoGue** [comment]
Hello @mahechine 
You can tell Brayns the custom directory where ZLib2 using **CMAKE_PREFIX_PATH**.
I compiled and installed the zlib repository you provided and was able to find and compile with it
`[cmake] -- Found BZip2: /home/nroman/Desktop/BZIP2INSTALL/lib/libbz2.so (found version "1.1.0") `

**Comment by mahechine** [comment]
> Hello @mahechine You can tell Brayns the custom directory where ZLib2 using **CMAKE_PREFIX_PATH**. I compiled and installed the zlib repository you provided and was able to find and compile with it `[cmake] -- Found BZip2: /home/nroman/Desktop/BZIP2INSTALL/lib/libbz2.so (found version "1.1.0") `


I forgot to mention that cmake was able to find BZip2. The problem is the compiler didn't. 

So I guess the BZIP2_INCLUDE_DIR isn't added to the project's include directories. 

Maybe you could uninstall bzip2 lib that in system path and then selecting your custom installed directory to compile to recurrent this error. 

I've seen this error half a year ago. Back then i just sudo apt installed bzip2 and error disappears. But this time i want to prevent using sudo and build as clean as possible.

**Comment by NadirRoGue** [comment]
You are correct, I've inspected the ninja.build and the BZip2 directory wasnt on the includes. PR #1192 fixes the issue.
Thanks!
