### ISSUE TITLE
Use subsampling to guarantee smooth interaction

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#330]
When interacting with the scene (camera rotation, changing lights, materials, DOF, ...), enable subsampling (blocks of 2x2 or 3x3 pixels) when the framerate drops below 15 fps. Revert back to full res rendering and start accumulating samples when there are no more changes.

**Comment by tribal-tec** [comment]
Should be done in the frontend and is possible already: set samplesPerPixel=-1 or -2, and check the FPS from the statistics message.

**Comment by straaljager** [comment]
Yep, I remember seeing it. I was wondering if Brayns could auto-detect when the framerate dips below say 10 fps and switch to blocky rendering without the users having to do that, otherwise they would first have to read the documentation (who reads that anyway) to know that setting samplesPerPixel to -1 is meaningful.

**Comment by tribal-tec** [comment]
Sauron/UI should have this encoded imo. Brayns should be dumb about such behavior. So yes, the user shouldn't do that manually (he could if wants to via python for instance), but when using the UI, this should be handled there.

**Comment by rolandjitsu** [comment]
So what you're saying is that when the user interacts with the camera we should set `samplesPerPixel` to `-1`? I already make some changes when user moves the camera so I can definitely add this param too.

**Comment by straaljager** [comment]
Yes, but only when the framerate is below a certain threshold (below 10 or 15 fps). Another way is to switch to a simpler rendering mode during interaction, e.g. ray casting only primary rays which is an order of magnitude faster than rendering with AO. That would allow the user to see the full res results all the time, which helps navigation of the scene.
  
AO mode: 
![dragon_ao_1](https://user-images.githubusercontent.com/13703350/36983079-bc014598-2091-11e8-8805-12b577e9ca8f.png)
Ray casting mode (only primary rays, no lighting):
![dragon_ao_basic](https://user-images.githubusercontent.com/13703350/36983081-bc1da10c-2091-11e8-88b7-44934b59ae80.png)

.

**Comment by tribal-tec** [comment]
All those things are possible to change with current API. It's matter to define under which conditions and which settings to change during interaction.

**Comment by straaljager** [comment]
Sounds good. I'd keep it simple and switch to 2x2 pixel blocks below 10 fps, and see if that works with a couple of different scenes.
