### ISSUE TITLE
Merge the histograms endpoints

### ISSUE THREAD

**Issue by rolandjitsu** [BlueBrain/Brayns#361]
Instead of having `/simulation-histogram` and `/volume-histogram` we should have a single `/histogram` endpoint.

If it's necessary to differentiate between the two, we can use the request body/params to do so.

**Comment by hernando** [comment]
It looks like this should be a plugin specific endpoint anyway and not part of the core API

**Comment by tribal-tec** [comment]
Will be solved automatically as the histogram will be per model, which is either a volume or geometry (for simulation historgram). So histogram becomes an RPC with the model ID as a parameter.

**Comment by tribal-tec** [comment]
Histograms are no longer exposed by Brayns
