### ISSUE TITLE
Add scene management

### ISSUE THREAD

**Issue by favreau** [BlueBrain/Brayns#363]
Make it possible to add, remove and modify "objects" in the scene. By objects, we understands things like circuits, volumes, meshes, point clouds, etc.
- Define a C++ API
- Define the pending REST/WS API
- Make it possible to have several instances of the same object, with different transformations.

**Comment by rolandjitsu** [comment]
Closing this as initial impl. has been added with https://github.com/BlueBrain/Brayns/pull/379.
