### ISSUE TITLE
Validate Ospray's path tracing shader

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#366]
The output from Embree's path tracer example code differs significantly from Ospray's (which looks strange). 

- Check whether Ospray's path tracer implementation is correct
- Compare to Embree, Blender Cycles or Mitsuba.

**Comment by karjonas** [comment]
Should this be closed now that we have our own path tracer?

**Comment by straaljager** [comment]
Indeed. We don't need Ospray's implementation anymore.
