### ISSUE TITLE
Use signed distance fields for approximating organic shapes (synapses, soma)

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#367]

**Comment by straaljager** [comment]
Some good examples here: http://iquilezles.org/www/articles/raymarchingdf/raymarchingdf.htm

**Comment by straaljager** [comment]
Path tracing through ray marching a signed distance field: [https://www.shadertoy.com/view/Xtt3Wn](https://www.shadertoy.com/view/Xtt3Wn) (very slow)

**Comment by tribal-tec** [comment]
Implemented in https://github.com/BlueBrain/Brayns/pull/391
