### ISSUE TITLE
Cannot connect to the renderer error

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#370]
Sauron/Brayns-UI displays the "Cannot connect to the renderer" a lot when running Brayns on my MacBook (connected via Wifi). Sometimes I see a brief glimpse of the default Cornell box before the error occurs, other times it appears straight away.

Restarted Docker a couple of times, but to no avail.

Used: http://brayns.ocp.bbp.epfl.ch/?host=localhost:8200 to run Brayns. Can this address handle multiple users at once?

**Comment by straaljager** [comment]
This error doesn't appear anymore with the latest dev branch, except when Docker runs out of memory (during BHV building)

**Comment by rolandjitsu** [comment]
Closing as no longer relevant.
