### ISSUE TITLE
Brayns build compilation fails on Ubuntu 16.04 with libuv-dev (0.10) installed

### ISSUE THREAD

**Issue by rdumusc** [BlueBrain/Brayns#390]
In file included from ../uvw/src/uvw/async.hpp:7:0,
                 from ../uvw/src/uvw.hpp:1,
                 from ../apps/BraynsService/main.cpp:28:
../uvw/src/uvw/event.hpp: In constructor ‘uvw::ErrorEvent::ErrorEvent(U)’:
../uvw/src/uvw/event.hpp:55:56: error: could not convert ‘((uvw::ErrorEvent*)this)->uvw::ErrorEvent::ec’ from ‘const int’ to ‘uv_err_t {aka uv_err_s}’
         : ec{static_cast<int>(val)}, str{uv_strerror(ec)}
                                                        ^
In file included from ../uvw/src/uvw/resource.hpp:8:0,
                 from ../uvw/src/uvw/handle.hpp:8,
                 from ../uvw/src/uvw/async.hpp:8,
                 from ../uvw/src/uvw.hpp:1,
                 from ../apps/BraynsService/main.cpp:28:
../uvw/src/uvw/loop.hpp: In static member function ‘static std::shared_ptr<uvw::Loop> uvw::Loop::create()’:
../uvw/src/uvw/loop.hpp:139:41: error: ‘uv_loop_init’ was not declared in this scope
         if(uv_loop_init(loop->loop.get())) {
                                         ^
In file included from ../uvw/src/uvw/resource.hpp:8:0,
                 from ../uvw/src/uvw/handle.hpp:8,
                 from ../uvw/src/uvw/async.hpp:8,
                 from ../uvw/src/uvw.hpp:1,
                 from ../apps/BraynsService/main.cpp:28:
../uvw/src/uvw/loop.hpp: In member function ‘void uvw::Loop::close()’:
../uvw/src/uvw/loop.hpp:254:44: error: ‘uv_loop_close’ was not declared in this scope
         auto err = uv_loop_close(loop.get());
                                            ^
../uvw/src/uvw/loop.hpp:255:41: error: no matching function for call to ‘uvw::ErrorEvent::ErrorEvent(<brace-enclosed initializer list>)’
         if(err) { publish(ErrorEvent{err}); }
                                         ^
In file included from ../uvw/src/uvw/async.hpp:7:0,
                 from ../uvw/src/uvw.hpp:1,
                 from ../apps/BraynsService/main.cpp:28:
../uvw/src/uvw/event.hpp:54:14: note: candidate: template<class U, class> uvw::ErrorEvent::ErrorEvent(U)
     explicit ErrorEvent(U val) noexcept
              ^
../uvw/src/uvw/event.hpp:54:14: note:   template argument deduction/substitution failed:
../uvw/src/uvw/event.hpp:52:8: note: candidate: constexpr uvw::ErrorEvent::ErrorEvent(const uvw::ErrorEvent&)
 struct ErrorEvent: Event<ErrorEvent> {
        ^
../uvw/src/uvw/event.hpp:52:8: note:   conversion of argument 1 would be ill-formed:
../uvw/src/uvw/event.hpp:52:8: note: candidate: constexpr uvw::ErrorEvent::ErrorEvent(uvw::ErrorEvent&&)
../uvw/src/uvw/event.hpp:52:8: note:   conversion of argument 1 would be ill-formed:
In file included from ../uvw/src/uvw/resource.hpp:8:0,
                 from ../uvw/src/uvw/handle.hpp:8,
                 from ../uvw/src/uvw/async.hpp:8,
                 from ../uvw/src/uvw.hpp:1,
                 from ../apps/BraynsService/main.cpp:28:
../uvw/src/uvw/loop.hpp: In member function ‘bool uvw::Loop::alive() const’:
../uvw/src/uvw/loop.hpp:288:42: error: ‘uv_loop_alive’ was not declared in this scope
         return !(uv_loop_alive(loop.get()) == 0);
                                          ^
compilation terminated due to -fmax-errors=5.

Expected: build succeeds, libuv support disabled by CMakeLists if neccessary.

**Comment by rdumusc** [comment]
Damn, I had installed the wrong one (libuv0.10-dev instead of libuv1-dev)... Yes, please add a CMake check to detect such problems.

**Comment by tribal-tec** [comment]
Added minimum libuv version in https://github.com/BlueBrain/Brayns/pull/392
