### ISSUE TITLE
Redesign rendermode settings panel

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#432]
The current render settings are non-intuitive: some settings only apply to certain rendermodes and there is currently a lot of trial and error needed to get things like AO working from the UI. Hard and soft shadow strength should be collapsed into one shadow parameter and a shadow on/off toggle. 

Proposal: 4 rendering modes:
- basic shading (with and without shadows)
- ambient occlusion (with and without shadows from direct lighting)
- path tracing (with and without shadows from direct lighting)
- special scientific rendermode: settings TBD

**Comment by rolandjitsu** [comment]
@straaljager Nobody has access to the UI yet, so UI issues make no sense to be opened here at this point 😉

And this goes beyond the UI, but we already have a pending issue in Trello which describes a task to have more contextual aware rendering params.

Let's take on this matter during a meeting.
