### ISSUE TITLE
Load binary volumes

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/Brayns#441]
Loading binary volumes (with 1 bit per voxel) in Brayns to allow loading huge volumes of neurons.

**Comment by jplanasc** [comment]
Hi @marwan-abdellah ,
Support for loading volumes (NRRD files) is now available in Brayns (develop branch for now, until we don't make a new release).
Unfortunately, the support of volumes with 1 bit per voxel won't be possible, as this is not supported by the ospray engine.
Thanks!
