### ISSUE TITLE
Apply clip planes to other cameras

### ISSUE THREAD

**Issue by rolandjitsu** [BlueBrain/Brayns#516]
Clip planes are currently applied only to `clippedperspective` camera. This should not be the case.

Clip planes should be applied to both the `perspective` and `orthographic` camera. And as a consequence, `clippedperspective` camera can be removed.

**Comment by hernando** [comment]
For clarification, clip planes are now a scene parameter. Clipping planes being a camera property in OSPRay is just an implementation detail.

**Comment by hernando** [comment]
Closed by #576
