### ISSUE TITLE
Expose camera as translation vector + rotation quaternion

### ISSUE THREAD

**Issue by rolandjitsu** [BlueBrain/Brayns#517]
Currently the camera is exposed as `{lookAt, origin, up}`, but this makes it difficult to work with when rotation operations are needed.

We should instead expose the camera as translation vector + rotation as a quaternion. As a consequence, rotation and translation operations can be achieved easier from the Python and/or JavaScript clients.

```json
{
  "translation": [0, 0, 1],
  "rotation": [0, 1, 0, 3.14]
}
```

**Comment by hernando** [comment]
Can we close this one?
