### ISSUE TITLE
Remove {detectionDistance} from simulation renderer

### ISSUE THREAD

**Issue by rolandjitsu** [BlueBrain/Brayns#522]
`detectionDistance` does not seem to have any effect on the rendering when used with the advanced simulation renderer.

It should probably be removed as it's most likely only a property of the proximity renderer.

**Comment by favreau** [comment]
You have to load circuits with meshes, and activate the simulation model to apply the simulation data to the meshes. If you don't do that, the parameter is indeed not used. So if you want to hide it, we need to expose a new property in the attributes that conditions their appearance in the UI depending on the dataset. We can discuss this offline if you want.

**Comment by rolandjitsu** [comment]
Ok, let's discuss this offline then.

**Comment by tribal-tec** [comment]
The option no longer exists in the current version of the CircuitViewerPlugin
