### ISSUE TITLE
Is it possible to reset the orientation of the models using a button or a button such as space? 

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/Brayns#567]
**Is your feature request related to a problem? Please describe.**
When I rotate the model, sometimes I might need to reset the orientation to generate multiple images for comparison. 

**Describe the solution you'd like**
A simple button in the UI or a key, for example space, to reset the orientation of the model.

**Describe alternatives you've considered**
Described above.

**Comment by tribal-tec** [comment]
- Press `Space` bar in braynsViewer
- Call `reset-camera()` from Python
- Press `Shift+R` from brayns UI or click on the ![Reset](https://material.io/tools/icons/static/icons/baseline-center_focus_strong-24px.svg) button
