### ISSUE TITLE
If all spheres centers are coplanar in an XYZ file, nothing gets rendererd.

### ISSUE THREAD

**Issue by hernando** [BlueBrain/Brayns#588]
A simple example:

     0 0 0
     1 0 0
     0 1 0
     1 1 0

Additionally, files without an end of line in the last line or empty lines are not accepted.

**Comment by hernando** [comment]
@tribal-tec What about fixing this one for the next release? Seems simple.

**Comment by tribal-tec** [comment]
I don't know if it's simple, but feel free to fix it then :smile:
