### ISSUE TITLE
Allowing users to add a gradient for the background. 

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/Brayns#736]
It would be nice to allow the user to define two or three colors to form a background gradient instead of a single color only. An example is given below.

![vasculature-brayns-2 copy](https://user-images.githubusercontent.com/1279443/53421021-2dc5bc80-39dd-11e9-97d0-f00c4ee14da3.png)

**Comment by straaljager** [comment]
Agreed, this could be a nice feature for publications or movies. I'm not sure if Ospray provides multiple background colours.

**Comment by tapaswenipathak** [comment]
Hi @marwan-abdellah, @straaljager, v. interested in this, I looked at few projects and I think Ospray enables multiple colors, can I work on this ticket? Is this ticket still open?

**Comment by jplanasc** [comment]
There are some technical limitations/challenges to implement this feature inside the rendering engine. We would need to add texture support, which was dropped with the latest refactorings. Plus, the colors would be affected by the lights of the scene, therefore not looking exactly like what the user would put.
After internal discussion with the development team, we think the best way to address this is to take a snapshot with transparent background and use an image editor to add the desired gradient as a post-processing step.
