### ISSUE TITLE
No simulation type in GUI.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/Brayns#753]
**Describe the bug**
When I provide a blueconfig as a model from the webGUI, there is no 'simulation' choice in the list of 'types'.
The best would be that it detects automatically that it is a 'circuit' if it gets a CircuitConfig and 'simulation' if it gets a BlueConfig. Based on the name should be enough for the time being.

**Comment by NadirRoGue** [comment]
This feature belongs to WebBrayns / BraynsCircuitStudio, since the UI is not part of Brayns anymore.
