### ISSUE TITLE
I want to download a movie of a circuit simulation

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/Brayns#754]
**Is your feature request related to a problem? Please describe.**
I would like to get a movie of a network simulation

**Describe the solution you'd like**
I load a simulation and instead of 'play', I click on a record button. then I click a 'stop' button. and then I can download a movie.

**Describe alternatives you've considered**
I can record my screen but it takes a huge amount of disk for nothing (the replay may take several seconds for each frame to get displayed for instance)

**Additional context**
I wanted a movie of a simulation of neocortex

**Comment by NadirRoGue** [comment]
Brayns now allow to generate movies from loaded models (including neuronal simulations), which will generate the frames on the same filesystem where brayns is being executed.
Download is not possible, as Brayns is not a webserver. The user must be able to fetch the frames / movie from the filesystem where they are written.

As an alternative, using scripting or manually in the Web UI, is possible to export single frames that can be downloaded.
