### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by Snektron** [BlueBrain/Brayns#780]
Hello,

for my bachelors' thesis i am writing ray tracing software which is similar to Brayns, and i would like to add Brayns under 'related work'. However i could not find any citation resources except the list of authors. What would be the proper way to cite Brayns?

Thanks

**Comment by NadirRoGue** [comment]
A bit late, and probably not useful for you anymore, but Brayns is now registered in Zenodo and has a DOI which can be found in the README.md of the brand **develop** (will be available in master on the next release)
