### ISSUE TITLE
Web UI: Incorrect snapshot viewport size when using zoomed browser

### ISSUE THREAD

**Issue by karjonas** [BlueBrain/Brayns#788]
**Describe the bug**
The viewport size in the web ui is incorrect if using a browser with zoomed size. 

**To Reproduce**
Press Ctrl+ a few times to zoom the browser.
Press the snapshot button.
Now width and height is incorrect and a fractional value.

**Expected behavior**
Correct width and height.

**Screenshots**
![image](https://user-images.githubusercontent.com/754587/60510184-1e2deb80-9ccf-11e9-9da5-a626c0ac8e8d.png)

**Comment by NadirRoGue** [comment]
The Web UI this issue refers to is obsolete and not supported anymore. Closing issue.
