### ISSUE TITLE
Web UI: Camera reset broken

### ISSUE THREAD

**Issue by karjonas** [BlueBrain/Brayns#792]
**Describe the bug**
The camera reset is broken for certain files.

**To Reproduce**
* Load the erato mesh from https://casual-effects.com/data/
* Click Reset Camera 

Now the camera gets positioned far away and you cannot see the model.

**Expected behavior**
I expect to see the model.

**Comment by NadirRoGue** [comment]
The web UI this issue refers to is obsolete and not supported anymore. Closing issue.
