### ISSUE TITLE
Web UI: Navigation Cube incorrectly rendered

### ISSUE THREAD

**Issue by karjonas** [BlueBrain/Brayns#798]
**Describe the bug**
The navigation cube is rendered incorrectly.

**To Reproduce**
Open Web UI and click on the navigation cube.

**Screenshots**
![image](https://user-images.githubusercontent.com/754587/61696010-ce25d000-ad34-11e9-955a-e984e9eb77e1.png)

**Comment by NadirRoGue** [comment]
This issue does not belong to Brayns itself, but to the UI. Furthermore, this UI is obsolete and will not be supported anymore. Closing issue.
