### ISSUE TITLE
Visualizing circuit of sonata data format

### ISSUE THREAD

**Issue by anirban6908** [BlueBrain/Brayns#835]
Hi,
I am moving from RTNeuron to using Brayns. I pulled the docker image and ran the web ui but when I add a model (.json [file](https://github.com/AllenInstitute/sonata/blob/master/examples/300_cells/circuit_config.json)) and use mesh type (or any type for that matter) I get unsupported type error. This is the same config file that produced the visualization for RTNeuron with `display_circuit` . Really appreciate any help on how to resolve this. 
Thanks

**Comment by ppodhajski** [comment]
Hello,
can you provide following details:
- brayns version
- startup parameters (command line)
- json file with the model

**Comment by anirban6908** [comment]
* Brayns 1.0.0 (8ff3a2c)
* Not sure what parameters you are referring to since I am running the container and using the web ui on chrome. Used the instruction from README, please let me know if I am doing something wrong.
* Here is the example network from the github sonata repo.
https://github.com/AllenInstitute/sonata/tree/master/examples/300_cells
the json file I am using is here
https://github.com/AllenInstitute/sonata/blob/master/examples/300_cells/circuit_config.json

Please let me know if you need anything else.

**Comment by NadirRoGue** [comment]
Latest release of Brayns has full support for the SONATA format. If you have any further issues with it, please, open a new issue.
