### ISSUE TITLE
Load morphology from memory not supported

### ISSUE THREAD

**Issue by w815526955** [BlueBrain/Brayns#894]
**Describe the bug**
When i use the UI to load swc model ,the UI feedback "Load morphology from memory not supported" to me.

**To Reproduce**
1. terminal docker run -ti --rm -p 8200:8200 bluebrain/brayns
2. terminal docker run -ti --rm -p 8080:8080 bluebrain/brayns-ui
3. load model from my conmuter
4. feedback error

**Expected behavior**
I hope the model uploads successfully

**Screenshots**

**Additional context**
nothing

**Comment by NadirRoGue** [comment]
I will close the issue since a solution was provided. If there are futher problems, please open a new ticket.
