### ISSUE TITLE
Add ZeroEQ as a git-submodule?

### ISSUE THREAD

**Issue by ingowald** [BlueBrain/Brayns#94]
Brayns automatically pulled _some_ packages, but ZeroEQ remains as a dependency I have to install manually . Is this intended?

**Comment by ingowald** [comment]
Note zeroeq doesn't even compile on my Ubuntu 1604. Filing separate issue on this right now.

**Comment by favreau** [comment]
When running cmake on Brayns, specifying -DINSTALL_PACKAGES=1 will automatically install the required dependencies. See https://github.com/Eyescale/CMake/blob/master/README.md for more information.
