### ISSUE TITLE
compile error w/ H5cpp.h

### ISSUE THREAD

**Issue by ingowald** [BlueBrain/Brayns#96]
cmake ../ -DBRAYNS_BRION_ENABLED=OFF -DBRAYNS_DEFLECT_ENABLED=OFF -DBRAYNS_IMAGEMAGICK_ENABLED=OFF -DBRAYNS_REST_ENABLED=OFF -DSUBPROJECT_Brion=OFF -DSUBPROJECT_Deflect=OFF -DSUBPROJECT_Keyv=OFF -DSUBPROJECT_Lexis=OFF -DSUBPROJECT_Lunchbox=OFF -DSUBPROJECT_MVDTool=OFF -DSUBPROJECT_ZeroBuf=OFF -DSUBPROJECT_ZeroEQ=OFF -DSUBPROJECT_cppnetlib=OFF

gives

[ 51%] Building CXX object brayns/io/CMakeFiles/braynsIO.dir/NESTLoader.cpp.o
/home/wald/Projects/Brayns/brayns/io/NESTLoader.cpp:28:19: fatal error: H5Cpp.h: No such file or directory

(note libhdf5-dev is installed:
wald@luchser:~/Projects/Brayns/bin$ ll /usr/include/hdf5/serial/H5Cpp.h 
-rw-r--r-- 1 root root 2.2k Apr  5  2016 /usr/include/hdf5/serial/H5Cpp.h
)

**Comment by favreau** [comment]
Thanks Ingo, It's a bug. In the NESTLoader.cpp file, it should read:
`
#ifdef BRAYNS_USE_BRION
#  include <H5Cpp.h>
#endif
`
Fixing it.

**Comment by favreau** [comment]
Fixed by https://github.com/BlueBrain/Brayns/pull/95
